openapi: 3.0.0
info:
  title: Concise API
  description: Main API for Concise application
  version: 1.0.0
servers:
  - url: http://HOST_IP:HOST_PORT
    description: Service API URI

paths:
  /:
    $ref: './paths/defaults/root.yaml'

  /auth/singup:
    $ref: './paths/auth/signup.yaml'

components:
  schemas:
    $ref: './schemas/_index.yaml'
  responses:
    $ref: './responses/_index.yaml'